name: Deploy static content to Pages

on:
  # ターゲットブランチにプッシュされた時に実行
  push:
    branches: ['main']
  # GitHub Actionsのタブから手動で実行可能にする
  workflow_dispatch:

# GitHub Pagesへのデプロイ権限を設定
permissions:
  contents: read
  pages: write
  id-token: write

# 複数回のデプロイが同時に実行されるのを防ぐ
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 一度のジョブでビルドとデプロイを行うための設定
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # デプロイするフォルダを指定
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
